### ISSUE TITLE
[v4r0] Error in JobMonitor from getSummary with dirac v7r0-pre18

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/WebAppDIRAC#333]
Not sure if the query from the WebApp, or the code in the JobMonitor is wrong
```
2019-07-11 09:05:57 UTC WorkloadManagement/JobMonitoring ERROR: Uncaught exception when serving RPC Function getJobPageSummaryWeb
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 279, in __RPCCallFunction
    uReturnValue = oMethod(*args)
  File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py", line 444, in export_getJobPageSummaryWeb
    if ((hbTime - lastTime) > 0 or jobDict['Status'] == "Stalled" or jobDict['MinorStatus'].startswith(
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
2019-07-11 09:05:57 UTC WorkloadManagement/JobMonitoring NOTICE: Returning response ([::ffff:128.142.128.61]:58516)[dirac_admin:sailer] (0.01 secs) ERROR: Server error while serving getJobPageSummaryWeb: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

**Comment by fstagni** [comment]
Maybe fixed already within https://github.com/DIRACGrid/DIRAC/pull/4163
