### ISSUE TITLE
SpaceOccupancy handler breaks when there are no SEs selected:

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/WebAppDIRAC#546]
In 7.3:

when clicking on "submit"

![image](https://user-images.githubusercontent.com/785576/135058790-3629f5ff-4175-4e57-a5bb-5d54773163b6.png)

```
HTTPServerRequest(protocol='https', host='lhcbvoboxcertif00.cern.ch', method='GET', uri='/DIRAC/s:LHCb-Certification/g:lhcb_prmgr/SpaceOccupancy/getSpaceOccupancyData?_dc=1632819775241&page=1&start=0&limit=25', version='HTTP/1.1', remote_ip='2001:1458:202:b7::102:96b2')
Traceback (most recent call last):
  File "/opt/dirac/versions/v10r3-pre4_1632816958/diracos/usr/lib64/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/dirac/versions/v10r3-pre4_1632816958/diracos/usr/lib64/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/dirac/versions/v10r3-pre4_1632816958/diracos/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/opt/dirac/versions/v10r3-pre4_1632816958/diracos/usr/lib64/python2.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/dirac/pro/WebAppDIRAC/WebApp/handler/SpaceOccupancyHandler.py", line 43, in web_getSpaceOccupancyData
    res = yield self.threadTask(rmc.selectSpaceTokenOccupancyCache, None, self.__requestParams())
  File "/opt/dirac/pro/WebAppDIRAC/WebApp/handler/SpaceOccupancyHandler.py", line 91, in __requestParams
    return list(json.loads(self.get_argument("StorageElement", "null")))
TypeError: 'NoneType' object is not iterable
```

**Comment by TaykYoku** [comment]
This should be fixed with #552.
